#######################################################################
#
# language section
#
language: node_js
node_js: 
  - 14

git:
  depth: false
#env:
#  - TRAVIS_BRANCH=main

#######################################################################
#
# ci run 
#
before_install:
  - npm install -g codecov  # needed only for codecov.io

script:
  - npm test # needed for basic travis build (otherwise, why bother)
  - npm run example-install # for doc generation
  - npm run docs
  - codecov  # needed only for codecov.io

#  - git branch

#######################################################################
#
# this sectiion is for deployment of the generated
# documentation to github pages
#
#before_deploy:
#  - if [ "$TRAVIS_BRANCH" == "main" ];then
#   git checkout main;
#    fi;

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./docs
  github_token: $GITHUB_TOKEN
  on:
    branch: main
